# Generated by Django 4.2.4 on 2023-08-31 18:58

from django.db import migrations, models
from divulgar.variaveis import para_adocao,adotado


class Migration(migrations.Migration):

    dependencies = [
        ('divulgar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[(adotado, adotado), (para_adocao, para_adocao)], default=para_adocao, max_length=20),
        ),
    ]
