# Generated by Django 4.2.4 on 2024-09-05 00:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divulgar', '0002_alter_pet_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adotar', '0003_pedido_adocao_email_adotante'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pedido_Adocao',
            new_name='PedidoAdocao',
        ),
    ]
